# Generated by Django 3.0 on 2021-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211226_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(max_length=800),
        ),
    ]
